LatestHardeep/Controllers/SetUpRaviFontController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LatestHardeep.Controllers
{
    public class SetUpRaviFontController : Controller
    {
        // GET: SetUpRaaviFont
        public ActionResult Windows7()
        {
            return View();
        }
        public ActionResult Win7video()
        {
            return View();
        }
        public ActionResult Win10video()
        {
            return View();
        }
        public ActionResult Windows10()
        {
            return View();
        }
    }
}

LatestHardeep/Views/SetUpRaviFont/Win10video.cshtml
@{
    ViewBag.Title = "Set up Punjabi Ravi Font in Windows 10";
}

@section Scripts
{
    <style type="text/css">
        video {
            width: 80%;
            height: auto;
            margin-left: 50px;
            margin-right: 50px;
        }
    </style>
}
<div class="row">
    <div class="text-center" style="margin-top:90px;margin-bottom:30px;">
        <h1 style="font-size:25px;">Complete Video to Set up Punjabi Ravi Font in Windows 10 </h1>
        <video controls="controls" width="480" controlsList="nodownload">
            <source src="~/Content/SetUpRavi/Windows%2010%20steps/Win10video.webm" type="video/webm" />
            <source src="~/Content/SetUpRavi/Windows%2010%20steps/Win10video.mp4" type="video/mp4" />
        </video>
    </div>
</div>

LatestHardeep/Views/SetUpRaviFont/Win7video.cshtml
@{
    ViewBag.Title = "Set up Punjabi Ravi Font in Windows 7";
}
@section Scripts
{
    <style type="text/css">
        video {
            width: 80%;
            height: auto;
            margin-left: 50px;
            margin-right: 50px;
        }
    </style>
}
<div class="row">
    <div class="text-center" style="margin-top:90px;margin-bottom:30px;">
        <h1 style="font-size:25px;">Complete Video to Set up Punjabi Ravi Font in Windows 7 </h1>
        <video controls="controls" width="480" controlsList="nodownload">
            <source src="~/Content/SetUpRavi/Windows%207%20steps/Win7.webm" type="video/webm" />
            <source src="~/Content/SetUpRavi/Windows%207%20steps/Win7.mp4" type="video/mp4" />
        </video>
    </div>
</div>

LatestHardeep/Views/SetUpRaviFont/Windows10.cshtml
@{
                /**/

                ViewBag.Title = "Set up Punjabi Ravi Font in Windows 10";
}

<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <!--add area here -->
        </div>
        <div class="col-sm-6">
            <h3 style="text-align:center;margin-top:90px;font-size:24px;"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;Steps to Set up Punjabi Ravi Font in Windows 10&nbsp;&nbsp;<br /><br /><span class="glyphicon glyphicon-play-circle"></span>&nbsp;&nbsp;@Html.ActionLink("Watch Video to Set Up ", "Win10video", "SetUpRaviFont")</h3>
            <div class="panel-group">
                <div class="panel panel-primary">
                    <div class="panel-heading">1. Click on Start Menu and Type "Region and Language" in the 'Search Area', then Click on "Language Settings".</div>

                    <div class="panel-body">
                        <img class="img-responsive" src="~/Content/SetUpRavi/Windows 10 steps/Win_10_1.png" />" />
                    </div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading">2. Click on "Add a preffered Language"</div>
                    <div class="panel-body">
                        <img class="img-responsive" src="~/Content/SetUpRavi/Windows 10 steps/Win_10_2.png" />
                    </div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        3. Under Choose a language to install, type 'Punjabi' and select 'Punjabi(Gurmukhi)'.
                    </div>
                    <div class="panel-body">
                        <img class="img-responsive" src="~/Content/SetUpRavi/Windows 10 steps/Win_10_3.png" />
                    </div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        4. Click on "Next"
                    </div>
                    <div class="panel-body">
                        <img class="img-responsive" src="~/Content/SetUpRavi/Windows 10 steps/Win_10_4.png" />
                    </div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        5. Click on "Install""
                    </div>
                    <div class="panel-body">
                        <img class="img-responsive" src="~/Content/SetUpRavi/Windows 10 steps/Win_10_5.png" />
                    </div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        6. Under "Preferred Languages", 'Punjabi' Language will be visible. Also, Click on 'EN' in taskbar to verify the installation.
                    </div>
                    <div class="panel-body">
                        <img class="img-responsive" src="~/Content/SetUpRavi/Windows 10 steps/Win_10_6.png" />
                    </div>
                </div>
               
            </div>
            <div class="col-sm-3">
                <!--add area here -->
            </div>
        </div>
    </div>
</div>

LatestHardeep/Views/SetUpRaviFont/Windows7.cshtml
@{

    ViewBag.Title = "Set up Punjabi Ravi Font in Windows 7";
}

<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <!--add area here -->

        </div>
        <div class="col-sm-6">
            <h1 style="text-align:center;margin-top:90px;font-size:24px;"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;Steps to Set up Punjabi Ravi Font in Windows 7&nbsp;&nbsp;<br /><br /><span class="glyphicon glyphicon-play-circle"></span>&nbsp;&nbsp;@Html.ActionLink("Watch Video to Set Up", "Win7video", "SetUpRaviFont")</h1>
            <div class="panel-group">
                <div class="panel panel-primary">
                    <div class="panel-heading">1. Click on Start Menu and Type "Region and Language" in the 'Search Area', then Click on "Region and Language".</div>

                    <div class="panel-body">
                        <img class="img-responsive" src="~/Content/SetUpRavi/Windows%207%20steps/Image1.JPG" alt="Step1" />
                    </div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading">2. Click on "Keyboard and Languages"</div>
                    <div class="panel-body">
                        <img src="~/Content/SetUpRavi/Windows%207%20steps/Image2.JPG" alt="Step2" />
                    </div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        3. Click on "Change keyboards"
                    </div>
                    <div class="panel-body">

                        <img src="~/Content/SetUpRavi/Windows%207%20steps/image3.JPG" alt="Step3" />
                    </div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        4. Click on "Add"
                    </div>
                    <div class="panel-body">

                        <img src="~/Content/SetUpRavi/Windows%207%20steps/image4.JPG" alt="Step4" />
                    </div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        5. Click on "Preview" to see the preview of "Punjabi Keyboard"
                    </div>
                    <div class="panel-body">

                        <img src="~/Content/SetUpRavi/Windows%207%20steps/image5.JPG" alt="Step5" />
                    </div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        6. Click on "Close"
                    </div>
                    <div class="panel-body">

                        <img src="~/Content/SetUpRavi/Windows%207%20steps/image6.JPG" alt="Step6" />
                    </div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        7. Click on "O.K"
                    </div>
                    <div class="panel-body">

                        <img src="~/Content/SetUpRavi/Windows%207%20steps/image7.JPG" alt="Step7" />
                    </div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        8. Click on "Apply"
                    </div>
                    <div class="panel-body">

                        <img src="~/Content/SetUpRavi/Windows%207%20steps/image8.JPG" alt="Step8" />
                    </div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        9. Click on "O.K"
                    </div>
                    <div class="panel-body">

                        <img src="~/Content/SetUpRavi/Windows%207%20steps/image9.JPG" alt="Step9" />
                    </div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        10. Click on "Keyboard Preferences" from the taskbar menu
                    </div>
                    <div class="panel-body">

                        <img src="~/Content/SetUpRavi/Windows%207%20steps/image10.JPG" alt="Step10" />
                    </div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        11. Click on "Punjabi(India)"
                    </div>
                    <div class="panel-body">

                        <img src="~/Content/SetUpRavi/Windows%207%20steps/image11.JPG" alt="Step11" />
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <!--add area here -->
            </div>
        </div>
    </div>
</div>