LatestHardeep/Controllers/EnglishIdiomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LatestHardeep.Controllers
{
    public class EnglishIdiomsController : Controller
    {
        // GET: EnglishIdioms
        public ActionResult Index(string id)
        {
            //Determine which page to display
            switch (id)
            {
                case "Page1":
                    return View("Page1");
                case "Page2":
                    return View("Page2");
                case "Page3":
                    return View("Page3");
                case "Page4":
                    return View("Page4");
                case "Page5":
                    return View("Page5");
                case "Page6":
                    return View("Page6");
                case "Page7":
                    return View("Page7");
                case "Page8":
                    return View("Page8");
                case "Page9":
                    return View("Page9");
                default:
                    return View("Index");
            }
           
        }
    }
}

LatestHardeep/Controllers/SscHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LatestHardeep.Controllers
{
    public class SscHistoryController : Controller
    {
        // GET: SscHistory
        public ActionResult Home(string id)
        {
            switch (id)
            {
                case "Page1":
                    return View("Page1");
                case "Page2":
                    return View("Page2");
                case "Page3":
                    return View("Page3");
                case "Page4":
                    return View("Page4");
                case "Page5":
                    return View("Page5");
                case "Page6":
                    return View("Page6");
                case "Page7":
                    return View("Page7");
                case "Page8":
                    return View("Page8");
                case "Page9":
                    return View("Page9");
                default:
                    return View("Index");
            }
        }
    }
}

LatestHardeep/Controllers/StartTypingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LatestHardeep.Controllers
{
    public class StartTypingController : Controller
    {
        // GET: StartTyping

        public ActionResult Index()
        {
            return View();
        }

     
        public ActionResult LearnTyping()
        {
            return View("LearnTyping");
        }

        public ActionResult PracticeTyping()
        {
            return View("PracticeTyping");
        }
    }
}

LatestHardeep/Controllers/TypingTipsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LatestHardeep.Controllers
{
    public class TypingTipsController : Controller
    {
        // GET: TypingTips

       
        public ActionResult TypingTips()
        {
            return View("Tips");
        }
       
    }
}

LatestHardeep/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Free Punjabi Ravi Font Typing</title>
    <meta name="description" content="Learn Punjabi Typing in Ravi font for free using typeinpunjabi.com. Useful for the preparation of typing tests for Punjab Government Jobs. Simple Row wise exercises for beginners and complete passage typing for advanced. Real time graphical results showing Accuracy, Gross Words per Minute, Net Words Per Minute. No software installation is required. Start practicing straight away from browser." />
    <meta name="keywords" content="punjabi typing, Type Punjabi Online, Punjabi Keyboard, Gurmukhi Keyboard, Punjabi Typewriter, Joy Punjabi, punjabi type master, punjabi typing master, punjabi typing master free download, Gurmukhi Typing, Punjabi Type Test, Punjabi Tutor, raavi font typing, punjabi typing software, typing software,punjabi typing software for pc, punjabi typing software raavi,punjabi typing software for windows 7 and windows 10,online punjabi typing speed test raavi,punjabi typing paragraph,punjabi typing practice,online punjabi typing mock test,online punjabi typing tutor raavi" />
    <meta name="author" content="Ravi Typing Tutor">
    <meta property="og:title" content="Free Punjabi Ravi Font Typing" />
    <meta property="og:description" content="Learn Punjabi Typing in Ravi font for free using typeinpunjabi.com. Useful for the preparation of typing tests for Punjab Government Jobs. Simple Row wise exercises for beginners and complete passage typing for advanced. Real time graphical results showing Accuracy, Gross Words per Minute, Net Words Per Minute. No software installation is required. Start practicing straight away from browser." />
    <meta property="og:type" content="website" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="icon" href="~/WebImage.ico" />
    <link href="~/Content/Footer-with-button-logo.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script type="text/javascript">

        function submitform() {
            if (!alert('you submitted the form!')) { window.location.reload(); }
        }

        //loader symbol code
        document.onreadystatechange = function () {
            if (document.readyState !== "complete") {
                document.querySelector(
                    "body").style.visibility = "hidden";
                document.querySelector(
                    "#loader").style.visibility = "visible";
            } else {
                document.querySelector(
                    "#loader").style.display = "none";
                document.querySelector(
                    "body").style.visibility = "visible";
            }
        };

    </script>

    <style type="text/css">

        /*loader css*/
        #loader {
            border: 12px solid #f3f3f3;
            border-radius: 50%;
            border-top: 12px solid #444444;
            width: 70px;
            height: 70px;
            animation: spin 1s linear infinite;
        }

        @@keyframes spin {
            100% {
                transform: rotate(360deg);
            }
        }

        .center {
            position: absolute;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            margin: auto;
        }

        dropdown-submenu {
            position: relative;
        }

        .dropdown-submenu > .dropdown-menu {
            top: 0;
            left: 100%;
            margin-top: -6px;
            margin-left: -1px;
            -webkit-border-radius: 0 6px 6px 6px;
            -moz-border-radius: 0 6px 6px 6px;
            border-radius: 0 6px 6px 6px;
        }

        .dropdown-submenu:hover > .dropdown-menu {
            display: block;
        }

        .dropdown-submenu > a:after {
            display: block;
            content: " ";
            float: right;
            width: 0;
            height: 0;
            border-color: transparent;
            border-style: solid;
            border-width: 5px 0 5px 5px;
            border-left-color: #cccccc;
            margin-top: 5px;
            margin-right: -10px;
        }

        .dropdown-submenu:hover > a:after {
            border-left-color: #ffffff;
        }

        .dropdown-submenu.pull-left {
            float: none;
        }

            .dropdown-submenu.pull-left > .dropdown-menu {
                left: -100%;
                margin-left: 10px;
                -webkit-border-radius: 6px 0 6px 6px;
                -moz-border-radius: 6px 0 6px 6px;
                border-radius: 6px 0 6px 6px;
            }
    </style>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-169363391-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());
        gtag('config', 'UA-169363391-1');
    </script>
</head>
<body>
    <div id="loader" class="center"></div>  

    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li class="@(ViewContext.RouteData.Values["Controller"].ToString() + ViewContext.RouteData.Values["Action"].ToString() == "HomeIndex" ? "active" : "")">@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
                <ul class="nav navbar-nav">
                    <li class="menu-item dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Set Up Ravi Font<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="@(ViewContext.RouteData.Values["Controller"].ToString() + ViewContext.RouteData.Values["Action"].ToString() == "SetUpRaviFontWindows7" ? "active" : "")">
                                @Html.ActionLink("Windows 7", "Windows7", "SetUpRaviFont")
                            </li>
                            <li class="@(ViewContext.RouteData.Values["Controller"].ToString() + ViewContext.RouteData.Values["Action"].ToString() == "SetUpRaviFontWindows10" ? "active" : "")">
                                @Html.ActionLink("Windows 10", "Windows10", "SetUpRaviFont")
                            </li>
                            @*<li class="menu-item">
                                    @Html.ActionLink("Typing Tips", "Tips", "TypingTips")
                                </li>*@
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li class="@(ViewContext.RouteData.Values["Controller"].ToString() + ViewContext.RouteData.Values["Action"].ToString() == "TypingTipsTypingTips" ? "active" : "")"> @Html.ActionLink("Typing Tips", "TypingTips", "TypingTips")</li>
                </ul>

                <ul class="nav navbar-nav">
                    <li class="@(ViewContext.RouteData.Values["Controller"].ToString() + ViewContext.RouteData.Values["Action"].ToString() == "StartTypingLearnTyping" ? "active" : "")">  @Html.ActionLink("Learn Typing", "LearnTyping", "StartTyping")</li>
                </ul>

                @*<ul class="nav navbar-nav">
                        <li>  @Html.ActionLink("English", "EnglishHome", "English")</li>
                    </ul>

                    <ul class="nav navbar-nav">
                        <li class="menu-item dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">History<b class="caret"></b></a>
                            <ul class="dropdown-menu">


                                <li class="menu-item">
                                    @Html.ActionLink("Previous year SSC", "Home", "SscHistory")
                                </li>
                                <li class="menu-item">
                                    @Html.ActionLink("Windows 10", "Index", "EnglishIdioms")
                                </li>
                            </ul>
                        </li>
                    </ul>*@



                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>

    @RenderBody()

    <footer id="myFooter">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <a href="@Url.Action("Index", "Home", null)">
                        <img src="~/img/Logo.png" alt="logo" style="margin-top:0px;">
                    </a>
                </div>
                <div class="col-sm-3">
                    <h5>About Us</h5>
                    <p>
                        We are a team of software professionals offering this website as a platform to help job aspirants crack punjabi typing test which is mandatory to become a Clerk under Punjab Government. Almost every clerical job in Punjab such as PSSSB, PSEB etc. requires efficient Punjabi typing. With this one can take a step ahead in his preparation journey to become a Punjab government employee.
                    </p>
                </div>
                <div class="col-sm-3">
                    <div class="social-networks">
                        @*<a href="#" class="twitter"><i class="fa fa-twitter"></i></a>*@
                        <a href="https://www.facebook.com/hardeepsingh.negi.7" class="facebook" target="_blank"><i class="fa fa-facebook"></i></a>
                        @* <a href="#" class="google"><i class="fa fa-google-plus"></i></a>*@
                        <h5>Follow Us</h5>
                    </div>
                    <div class="counter" style="text-align:center;">
                        <p class="counter-count">@(Global.totalNumberOfUsers)</p>
                        <p class="counter-p">Visitor No</p>
                    </div>
                </div>
                <div class="col-sm-3">

                    <form method="post" action="https://submit-form.com/FlVpLFjdKtuOi9L_rNvXD">

                        <input type="hidden"
                               name="_feedback.success.title"
                               value="Your Feedback submitted successfullly!" />
                        @* Implement captcha checkbox, once website is published to avoid spamming *@
                        <h5>Drop us a Message</h5>
                        <div class="input-container" style="display:-ms-flexbox;display:flex;margin-bottom:10px;text-align:center;">
                            <i class="fa fa-user icon" style="padding:10px;color:white;background:dodgerblue;min-width:50px;text-align:center;"></i>
                            <input class="input-field" type="text" placeholder="Name" name="name" required style="color:black;padding:2px;width:100%">
                        </div>

                        <div class="input-container" style="display:-ms-flexbox;display:flex;margin-bottom:10px;text-align:center;">
                            <i class="fa fa-envelope icon" style="padding:10px;color:white;background:dodgerblue;min-width:50px;text-align:center;"></i>
                            <input class="input-field" type="email" placeholder="Email" name="email" required style="color:black;padding:2px;width:100%;">
                        </div>

                        <div class="input-container" style="display:-ms-flexbox;display:flex;margin-bottom:10px;text-align:center;height:100px;">
                            <span class="glyphicon glyphicon-pencil" style="padding:10px;color:white;background:dodgerblue;min-width:50px;text-align:center;"></span>
                            <textarea class="input-field" type="text" placeholder="Message" name="text" required style="color:black;padding:2px;width:100%;resize:none;"></textarea>
                        </div>
                        <button type="submit" class="btn">Send</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="cotainer">
            <div class="footer-copyright">
                <p>&copy; @DateTime.Now.Year - www.typeinpunjabi.com</p><span>@Html.ActionLink("Disclaimer", "Disclaimer", "Home")</span>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>